force-app/main/default/objects/MonthlyInputRow__c/MonthlyInputRow__c.object-meta.xml
<CustomObject>
    <label>[FTD]Monthly Input Row</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>[FTD]Monthly Input Rows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MonthlyInputRow__c/fields/Category3__c.field-meta.xml
<CustomField>
    <fullName>Category3__c</fullName>
    <label>Category3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MonthlyInputRow__c/fields/MonthlyReport__c.field-meta.xml
<CustomField>
    <fullName>MonthlyReport__c</fullName>
    <label>Monthly Report</label>
    <referenceTo>MonthlyReport__c</referenceTo>
    <relationshipLabel>Monthly Input Rows</relationshipLabel>
    <relationshipName>MonthlyInputRows</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/MonthlyReport__c/MonthlyReport__c.object-meta.xml
<CustomObject>
    <label>[FTD]Monthly Report</label>
    <nameField>
        <label>Month</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>[FTD]Monthly Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MonthlyReport__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <summarizedField>MonthlyInputRow__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>MonthlyInputRow__c.Category1__c</field>
        <operation>equals</operation>
        <value>楽天銀行,クレカ</value>
    </summaryFilterItems>
    <summaryForeignKey>MonthlyInputRow__c.MonthlyReport__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/MonthlyInputRowTriggerTest.cls
@isTest
private class MonthlyInputRowTriggerTest {
    @isTest static void testNameGeneration() {
        MonthlyReport__c report = new MonthlyReport__c(Name = '202405');
        insert report;

        MonthlyInputRow__c row = new MonthlyInputRow__c(
            MonthlyReport__c = report.Id,
            Category3__c = 'sample_key',
            Amount__c = 10
        );
        insert row;

        row = [SELECT Name FROM MonthlyInputRow__c WHERE Id = :row.Id];
        System.assertEquals('2405-sample_key', row.Name);

        row.Category3__c = 'changed_key';
        update row;

        row = [SELECT Name FROM MonthlyInputRow__c WHERE Id = :row.Id];
        System.assertEquals('2405-changed_key', row.Name);
    }
}